### ISSUE TITLE
Launching server and client as described in the quickstart fail

### ISSUE THREAD

**Issue by rubenfiszel** [openai/gym-http-api#2]
Step to reproduce:
`python2 gym_http_server.py `
and in another terminal
`python2 gym_http_client.py `
or 
`python2 example_agent.py `

server terminal output:
```
[2016-07-02 19:05:15,513] Making new env: CartPole-v0
[2016-07-02 19:05:15,527] Creating monitor directory /tmp/random-agent-results
[2016-07-02 19:05:15,530] Starting new video recorder writing to /tmp/random-agent-results/openaigym.video.0.17805.video000000.mp4
[2016-07-02 19:05:15,918] ERROR in app: Exception on /v1/envs/5bd5d0fb/reset/ [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "gym_http_server.py", line 189, in env_reset
    observation = envs.reset(instance_id)
  File "gym_http_server.py", line 54, in reset
    obs = env.reset()
  File "/usr/lib/python2.7/site-packages/gym/core.py", line 124, in reset
    self.monitor._after_reset(observation)
  File "/usr/lib/python2.7/site-packages/gym/monitoring/monitor.py", line 248, in _after_reset
    self.video_recorder.capture_frame()
  File "/usr/lib/python2.7/site-packages/gym/monitoring/video_recorder.py", line 105, in capture_frame
    frame = self.env.render(mode=render_mode)
  File "/usr/lib/python2.7/site-packages/gym/core.py", line 175, in render
    return self._render(mode=mode, close=close)
  File "/usr/lib/python2.7/site-packages/gym/envs/classic_control/cartpole.py", line 141, in _render
    return self.viewer.get_array()
  File "/usr/lib/python2.7/site-packages/gym/envs/classic_control/rendering.py", line 107, in get_array
    arr = arr.reshape(self.height, self.width, 4)
ValueError: total size of new array must be unchanged
[2016-07-02 19:05:15,918] Exception on /v1/envs/5bd5d0fb/reset/ [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "gym_http_server.py", line 189, in env_reset
    observation = envs.reset(instance_id)
  File "gym_http_server.py", line 54, in reset
    obs = env.reset()
  File "/usr/lib/python2.7/site-packages/gym/core.py", line 124, in reset
    self.monitor._after_reset(observation)
  File "/usr/lib/python2.7/site-packages/gym/monitoring/monitor.py", line 248, in _after_reset
    self.video_recorder.capture_frame()
  File "/usr/lib/python2.7/site-packages/gym/monitoring/video_recorder.py", line 105, in capture_frame
    frame = self.env.render(mode=render_mode)
  File "/usr/lib/python2.7/site-packages/gym/core.py", line 175, in render
    return self._render(mode=mode, close=close)
  File "/usr/lib/python2.7/site-packages/gym/envs/classic_control/cartpole.py", line 141, in _render
    return self.viewer.get_array()
  File "/usr/lib/python2.7/site-packages/gym/envs/classic_control/rendering.py", line 107, in get_array
    arr = arr.reshape(self.height, self.width, 4)
ValueError: total size of new array must be unchanged
^C[2016-07-02 19:05:22,624] Finished writing results. You can upload them to the scoreboard via gym.upload(u'/tmp/random-agent-results')
```

**Comment by catherio** [comment]
Thanks for the bug report!

When I run those commands, I do not get the same error. It looks like the problem is not specific to the HTTP API, but rather, is a generic gym error relating to monitoring and rendering.  I see a similar issue that was fixed in commit in May, which makes me think that updating might resolve your troubles: https://github.com/openai/gym/issues/95

Can you double-check that you have pulled the most recent version of gym, and also that you have all the gym dependencies (for example, using 'pip install gym[all]'), and then try running those commands again?

If you already have the latest versions of everything, or if the problem persists after updating, then we can dive a little deeper. One possible next step would be to run the monitoring tests in the gym package and to share the output:
>> cd /usr/lib/python2.7/site-packages/gym/monitoring/tests
>> nose2 test_monitor

**Comment by rubenfiszel** [comment]
Hello,

I solved the issue long ago. I forgot to close the issue. Thanks for the reply.
