### ISSUE TITLE
Fail to run 'HandManipulateBlock-v0'

### ISSUE THREAD

**Issue by navid-hoseini** [openai/gym-http-api#69]
Thanks for the nice api. I managed to run `CartPole-v0` using `python example_agent.py` command. Now I need to run `HandManipulateBlock-v0`. But this environment is not available in gym 0.7.4 (specified in `requirements.txt`). So I changed the versions of numpy, gym and requests in `requirements.txt` to the following:
numpy==1.15.0,
gym==0.10.5,
requests==2.19.1
Now `gym-http-api` recognizes `HandManipulateBlock-v0` environment. But when I try to run the environment using `python example_agent.py`, the execution halts with the followint exception:

Traceback (most recent call last):
  File "/home/navid/gym-http-api/gym_http_client.py", line 22, in _parse_server_error_or_raise_for_status
    j = resp.json()
  File "/home/navid/my-gym-http-api/lib/python3.5/site-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Could anyone give me some hint about how to fix this? Thanks.
Best regards,
Navid

**Comment by machinaut** [comment]
We don't use the HTTP API internally, so it hasn't got much attention lately.

What's your use case for needing it?  Could you use the regular (python) api instead?

**Comment by BoltzmannBrain** [comment]
Thanks for following up @machinaut. The rest of my code (i.e. the "agent") is in C++. I could write bindings s.t. the experiments are run with the standard gym python api, passing observations/actions to/from the C++ agent, but I was hoping to avoid that by using this repo.

**Comment by machinaut** [comment]
I think there isn't currently an effort to maintain this repo, so I would recommend using it as-is with older packages if the older environments are sufficient for your needs.

If you need the newer mujoco environments, then I would recommend looking at a different way of communicating with the python API.

I've personally had a lot of success integrating c++ and python code by making the C++ code into modules using the C extension api: https://docs.python.org/3/c-api/intro.html

**Comment by BoltzmannBrain** [comment]
Okay, not a problem, but I would suggest adding a note to the README:
> This repo is not actively supported beyond commit ___. Proceed at your own risk if using package version greater than those defined in requirements.txt, as some gym/mujoco functions and environments may not be useable.

And yes I'm familiar with the C extension API, having used it with [Boost.Python](https://www.boost.org/doc/libs/1_68_0/libs/python/doc/html/index.html) and [pybind](https://github.com/pybind/pybind11). If I end up implementing the bindings, would this be desired functionality for the gym repo?
