### ISSUE TITLE
Need update

### ISSUE THREAD

**Issue by Charele** [openai/gym-http-api#75]
Can someone update this project for non-Python coder?
For example, support Python3.x, support  newer gym version?

python gym_http_client.py

Traceback (most recent call last):
  File "gym_http_client.py", line 22, in _parse_server_error_or_raise_for_status
    j = resp.json()
  File "C:\Miniconda3\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Miniconda3\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Miniconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Miniconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gym_http_client.py", line 154, in <module>
    obs_info = client.env_observation_space_info(instance_id)
  File "gym_http_client.py", line 95, in env_observation_space_info
    resp = self._get_request(route)
  File "gym_http_client.py", line 44, in _get_request
    return self._parse_server_error_or_raise_for_status(resp)
  File "gym_http_client.py", line 27, in _parse_server_error_or_raise_for_status
    resp.raise_for_status()
  File "C:\Miniconda3\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://127.0.0.1:5000/v1/envs/da42e4bc/observation_space/

**Comment by cagneymoreau** [comment]
Here is an update I made for myself for dl4j and python 3
https://github.com/cagneymoreau/gym-http-api
