### ISSUE TITLE
Launching server and client as described in the quickstart fail

### ISSUE THREAD

**Issue by rubenfiszel** [openai/gym-http-api#8]
```
 python2 gym_http_server.py                 
[2016-08-10 13:26:44,003] Making new env: CartPole-v0              
[2016-08-10 13:26:44,016] Creating monitor directory /tmp/random-agent-results
[2016-08-10 13:26:44,019] Starting new video recorder writing to /tmp/random-agent-results/openaigym.video.0.1490.video000000.mp4
[2016-08-10 13:26:44,378] ERROR in app: Exception on /v1/envs/2e1c7bd7/reset/ [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "gym_http_server.py", line 193, in env_reset
    observation = envs.reset(instance_id)
  File "gym_http_server.py", line 54, in reset
    obs = env.reset()
  File "/usr/lib/python2.7/site-packages/gym/core.py", line 124, in reset
    self.monitor._after_reset(observation)
  File "/usr/lib/python2.7/site-packages/gym/monitoring/monitor.py", line 248, in _after_reset
    self.video_recorder.capture_frame()
  File "/usr/lib/python2.7/site-packages/gym/monitoring/video_recorder.py", line 105, in capture_frame
    frame = self.env.render(mode=render_mode)
  File "/usr/lib/python2.7/site-packages/gym/core.py", line 175, in render
    return self._render(mode=mode, close=close)
  File "/usr/lib/python2.7/site-packages/gym/envs/classic_control/cartpole.py", line 141, in _render
    return self.viewer.get_array()
  File "/usr/lib/python2.7/site-packages/gym/envs/classic_control/rendering.py", line 107, in get_array
    arr = arr.reshape(self.height, self.width, 4)
ValueError: total size of new array must be unchanged
[2016-08-10 13:26:44,378] Exception on /v1/envs/2e1c7bd7/reset/ [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "gym_http_server.py", line 193, in env_reset
    observation = envs.reset(instance_id)
  File "gym_http_server.py", line 54, in reset
    obs = env.reset()
  File "/usr/lib/python2.7/site-packages/gym/core.py", line 124, in reset
    self.monitor._after_reset(observation)
  File "/usr/lib/python2.7/site-packages/gym/monitoring/monitor.py", line 248, in _after_reset
    self.video_recorder.capture_frame()
  File "/usr/lib/python2.7/site-packages/gym/monitoring/video_recorder.py", line 105, in capture_frame
    frame = self.env.render(mode=render_mode)
  File "/usr/lib/python2.7/site-packages/gym/core.py", line 175, in render
    return self._render(mode=mode, close=close)
  File "/usr/lib/python2.7/site-packages/gym/envs/classic_control/cartpole.py", line 141, in _render
    return self.viewer.get_array()
  File "/usr/lib/python2.7/site-packages/gym/envs/classic_control/rendering.py", line 107, in get_array
    arr = arr.reshape(self.height, self.width, 4)
ValueError: total size of new array must be unchanged
^C[2016-08-10 13:26:53,774] Finished writing results. You can upload them to the scoreboard via gym.upload(u'/tmp/random-agent-results')

```

**Comment by rubenfiszel** [comment]
work with the latest gym
